In [1]:
#1
from urllib.request import urlopen
from bs4 import BeautifulSoup
html = urlopen('https://en.wikipedia.org/wiki/Main_Page')
bs = BeautifulSoup(html, "html.parser")
titles = bs.find_all(['h1', 'h2','h3','h4','h5','h6'])
print('List all the header tags :', *titles, sep='\n\n')

List all the header tags :

<h1 class="firstHeading mw-first-heading" id="firstHeading" style="display: none">Main Page</h1>

<h1><span class="mw-headline" id="Welcome_to_Wikipedia">Welcome to <a href="/wiki/Wikipedia" title="Wikipedia">Wikipedia</a></span></h1>

<h2 class="mp-h2" id="mp-tfa-h2"><span id="From_today.27s_featured_article"></span><span class="mw-headline" id="From_today's_featured_article">From today's featured article</span></h2>

<h2 class="mp-h2" id="mp-dyk-h2"><span class="mw-headline" id="Did_you_know_...">Did you know ...</span></h2>

<h2 class="mp-h2" id="mp-itn-h2"><span class="mw-headline" id="In_the_news">In the news</span></h2>

<h2 class="mp-h2" id="mp-otd-h2"><span class="mw-headline" id="On_this_day">On this day</span></h2>

<h2 class="mp-h2" id="mp-tfp-h2"><span id="Today.27s_featured_picture"></span><span class="mw-headline" id="Today's_featured_picture">Today's featured picture</span></h2>

<h2 class="mp-h2" id="mp-other"><span class="mw-headline" id="Other_areas_of_Wikipedia">Other areas of Wikipedia</span></h2>

<h2 class="mp-h2" id="mp-sister"><span id="Wikipedia.27s_sister_projects"></span><span class="mw-headline" id="Wikipedia's_sister_projects">Wikipedia's sister projects</span></h2>

<h2 class="mp-h2" id="mp-lang"><span class="mw-headline" id="Wikipedia_languages">Wikipedia languages</span></h2>

<h2>Navigation menu</h2>

<h3 class="vector-menu-heading" id="p-personal-label">
<span class="vector-menu-heading-label">Personal tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-namespaces-label">
<span class="vector-menu-heading-label">Namespaces</span>
</h3>

<h3 class="vector-menu-heading" id="p-views-label">
<span class="vector-menu-heading-label">Views</span>
</h3>

<h3>
<label for="searchInput">Search</label>
</h3>

<h3 class="vector-menu-heading" id="p-navigation-label">
<span class="vector-menu-heading-label">Navigation</span>
</h3>

<h3 class="vector-menu-heading" id="p-interaction-label">
<span class="vector-menu-heading-label">Contribute</span>
</h3>

<h3 class="vector-menu-heading" id="p-tb-label">
<span class="vector-menu-heading-label">Tools</span>
</h3>

<h3 class="vector-menu-heading" id="p-coll-print_export-label">
<span class="vector-menu-heading-label">Print/export</span>
</h3>

<h3 class="vector-menu-heading" id="p-wikibase-otherprojects-label">
<span class="vector-menu-heading-label">In other projects</span>
</h3>

<h3 class="vector-menu-heading" id="p-lang-label">
<span class="vector-menu-heading-label">Languages</span>
</h3>

In [12]:
#2
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd

url = 'https://www.imdb.com/chart/top'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
crew = [a.attrs.get('title') for a in soup.select('td.titleColumn a')]
ratings = [b.attrs.get('data-value')
        for b in soup.select('td.posterColumn span[name=ir]')]
 

list = []
 
for index in range(0, len(movies)):

    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    data = {"movie_title": movie_title,
            "rating": ratings[index],
            "year": year,}
    list.append(data)

for movie in list:
    print(movie['movie_title'], '('+movie['year'] +
        ') -', movie['rating'])
 
 
df = pd.DataFrame(list)
df.to_csv('imdb_top_100_movies.csv',index=False)

The Shawshank Redemption (1994) - 9.234669879350566
The Godfather (1972) - 9.156547015103307
The Dark Knight (2008) - 8.987384924562248
The Godfather Part II (1974) - 8.98456571597942
12 Angry Men (1957) - 8.949208668234776
Schindler's List (1993) - 8.93633457017988
The Lord of the Rings: The Return of the King (2003) - 8.92339601155943
Pulp Fiction (1994) - 8.84973482234196
The Lord of the Rings: The Fellowship of the Ring (2001) - 8.80486792058216
 Il buono, il brutto, il cattivo (1966) - 8.792676303189452
Forrest Gump (1994) - 8.767708522596246
Fight Club (1999) - 8.749243963650041
Inception (2010) - 8.73300743118968
The Lord of the Rings: The Two Towers (2002) - 8.729567933147555
The Empire Strikes Back (1980) - 8.701385274802474
The Matrix (1999) - 8.670546716613993
Goodfellas (1990) - 8.652603319640944
One Flew Over the Cuckoo's Nest (1975) - 8.640355814724616
Se7en (1995) - 8.604373689620903
Shichinin no samurai (1954) - 8.59901843279163
It's a Wonderful Life (1946) - 8.59692577153818
The Silence of the Lambs (1991) - 8.588316372688023
Cidade de Deus (2002) - 8.578955056117282
Saving Private Ryan (1998) - 8.578594046403442
La vita è bella (1997) - 8.566383544087246
The Green Mile (1999) - 8.560758925655678
Interstellar (2014) - 8.559448498141087
Star Wars (1977) - 8.553026390913091
Terminator 2: Judgment Day (1991) - 8.53645263329418
Back to the Future (1985) - 8.518328353523932
Sen to Chihiro no kamikakushi (2001) - 8.515316258230333
Psycho (1960) - 8.50827452147868
The Pianist (2002) - 8.505445739535363
Léon (1994) - 8.498779045172267
Gisaengchung (2019) - 8.496156691641698
The Lion King (1994) - 8.488383954865794
Gladiator (2000) - 8.4863369182439
American History X (1998) - 8.483895496845907
The Departed (2006) - 8.475712682473207
The Usual Suspects (1995) - 8.474771923135158
The Prestige (2006) - 8.468498799066516
Casablanca (1942) - 8.464481469242749
Whiplash (2014) - 8.462287829705598
The Intouchables (2011) - 8.45345852573786
Seppuku (1962) - 8.450760887843124
Hotaru no haka (1988) - 8.450496814427492
Modern Times (1936) - 8.449197482018723
Once Upon a Time in the West (1968) - 8.446765517334962
Rear Window (1954) - 8.437198080412546
Alien (1979) - 8.435178734691462
City Lights (1931) - 8.434320998799944
Nuovo Cinema Paradiso (1988) - 8.431093275450324
Apocalypse Now (1979) - 8.424920960867562
Memento (2000) - 8.424549783178833
Raiders of the Lost Ark (1981) - 8.41101670108542
Top Gun: Maverick (2022) - 8.407527534390349
Django Unchained (2012) - 8.40407084952307
WALL·E (2008) - 8.39330515929691
The Lives of Others (2006) - 8.385860072661899
Sunset Blvd (1950) - 8.38305969033806
Paths of Glory (1957) - 8.371742778766656
The Shining (1980) - 8.367137626894865
The Great Dictator (1940) - 8.365956076432978
Witness for the Prosecution (1957) - 8.359186974974213
Avengers: Infinity War (2018) - 8.358237062457654
Aliens (1986) - 8.344658194992517
American Beauty (1999) - 8.335998028229518
Dr Strangelove or: How I Learned to Stop Worrying and Love the Bomb (1964) - 8.332350197078945
Spider-Man: Into the Spider-Verse (2018) - 8.330715128021549
The Dark Knight Rises (2012) - 8.328142715202901
Oldeuboi (2003) - 8.320083064821704
Joker (2019) - 8.317966954864008
Amadeus (1984) - 8.316019610142602
Braveheart (1995) - 8.315499470917047
Toy Story (1995) - 8.315039340020485
Coco (2017) - 8.312939999705385
Inglourious Basterds (2009) - 8.312715266256738
Das Boot (1981) - 8.312619555620943
Mononoke-hime (1997) - 8.303493770618854
Avengers: Endgame (2019) - 8.30184458568492
Once Upon a Time in America (1984) - 8.298322662534538
Good Will Hunting (1997) - 8.287891971347776
Kimi no na wa (2016) - 8.27750094159765
Requiem for a Dream (2000) - 8.275719640286004
Toy Story 3 (2010) - 8.27570157045515
Singin' in the Rain (1952) - 8.273516958542
3 Idiots (2009) - 8.270646698311628
Star Wars: Episode VI - Return of the Jedi (1983) - 8.267096544870364
Tengoku to jigoku (1963) - 8.266462530509319
2001: A Space Odyssey (1968) - 8.264061239655218
Eternal Sunshine of the Spotless Mind (2004) - 8.263438606460705
Reservoir Dogs (1992) - 8.263227257809389
Capharnaüm (2018) - 8.259697726932831
Lawrence of Arabia (1962) - 8.256363679847485
Citizen Kane (1941) - 8.25631112729943
Jagten (2012) - 8.255903331843319
M - Eine Stadt sucht einen Mörder (1931) - 8.254301439706996
North by Northwest (1959) - 8.252221350364067
Idi i smotri (1985) - 8.247560564948795
 Vertigo (1958) - 8.246823754677246
Le fabuleux destin d'Amélie Poulain (2001) - 8.244324485543954
A Clockwork Orange (1971) - 8.24313346065186
Double Indemnity (1944) - 8.239599185582323
Full Metal Jacket (1987) - 8.239578417623393
The Apartment (1960) - 8.238994917306352
Scarface (1983) - 8.2356126357561
Ikiru (1952) - 8.235027523498891
The Sting (1973) - 8.228763344383866
To Kill a Mockingbird (1962) - 8.228422389639256
Taxi Driver (1976) - 8.225755842881568
Heat (1995) - 8.22481810476929
Up (2009) - 8.224554986953459
LA Confidential (1997) - 8.223118546143462
Metropolis (1927) - 8.221818654154198
Incendies (2010) - 8.221380332633874
Jodaeiye Nader az Simin (2011) - 8.221123385101771
Die Hard (1988) - 8.220160008291053
Snatch (2000) - 8.219785361421362
Indiana Jones and the Last Crusade (1989) - 8.21842731846781
Ladri di biciclette (1948) - 8.218048455282053
Hamilton (2020) - 8.216494619811268
1917 (2019) - 8.21176899784801
Taare Zameen Par (2007) - 8.208179920378667
Der Untergang (2004) - 8.204871475261529
Per qualche dollaro in più (1965) - 8.202580773443733
Batman Begins (2005) - 8.201256807496696
Dangal (2016) - 8.198711218678493
The Kid (1921) - 8.194021303245226
Some Like It Hot (1959) - 8.192143775511843
All About Eve (1950) - 8.181142516717506
The Father (2020) - 8.18087551188549
Green Book (2018) - 8.17510737648875
Spider-Man: No Way Home (2021) - 8.174531357804927
The Wolf of Wall Street (2013) - 8.173263655886466
Judgment at Nuremberg (1961) - 8.170468616832244
Ran (1985) - 8.165373223617937
Casino (1995) - 8.164158642024871
Unforgiven (1992) - 8.163798219769447
Pan's Labyrinth (2006) - 8.162550506031307
There Will Be Blood (2007) - 8.156676022625616
The Sixth Sense (1999) - 8.154114121559225
The Truman Show (1998) - 8.15408256864993
A Beautiful Mind (2001) - 8.152639921450596
Monty Python and the Holy Grail (1975) - 8.150625643954333
Yôjinbô (1961) - 8.149761757562397
The Treasure of the Sierra Madre (1948) - 8.149092804215611
Shutter Island (2010) - 8.145543344446365
Jurassic Park (1993) - 8.145042153608717
The Great Escape (1963) - 8.142650367028562
Rashômon (1950) - 8.142347018462196
Kill Bill: Vol 1 (2003) - 8.137873371882147
No Country for Old Men (2007) - 8.136978736612743
Finding Nemo (2003) - 8.131510141063432
The Elephant Man (1980) - 8.13027805180601
Chinatown (1974) - 8.129455341824123
Raging Bull (1980) - 8.129026829714448
The Thing (1982) - 8.127707263308016
Gone with the Wind (1939) - 8.12601363588547
V for Vendetta (2005) - 8.125063370499074
Inside Out (2015) - 8.12332743097956
Lock, Stock and Two Smoking Barrels (1998) - 8.122670267203528
Dial M for Murder (1954) - 8.120355723164934
El secreto de sus ojos (2009) - 8.117812749463615
Hauru no ugoku shiro (2004) - 8.114851385529422
The Bridge on the River Kwai (1957) - 8.113828295851206
Three Billboards Outside Ebbing, Missouri (2017) - 8.111192801908661
Trainspotting (1996) - 8.110987452724185
Warrior (2011) - 8.104426742607538
Gran Torino (2008) - 8.1043322072465
Fargo (1996) - 8.103165394443833
Prisoners (2013) - 8.098103736406294
Tonari no Totoro (1988) - 8.094431849292603
Million Dollar Baby (2004) - 8.089676195678608
Catch Me If You Can (2002) - 8.087733671354611
The Gold Rush (1925) - 8.087102974568346
Blade Runner (1982) - 8.085829099229006
Everything Everywhere All at Once (2022) - 8.084787718731937
On the Waterfront (1954) - 8.083816979461416
Bacheha-Ye aseman (1997) - 8.082861264427123
The Third Man (1949) - 8.08135117657671
Ben-Hur (1959) - 8.079129009111085
Before Sunrise (1995) - 8.078940398675378
12 Years a Slave (2013) - 8.078306737739283
Smultronstället (1957) - 8.078175728706489
The General (1926) - 8.077699563148126
Gone Girl (2014) - 8.077260771789097
Harry Potter and the Deathly Hallows: Part 2 (2011) - 8.077155611752795
The Deer Hunter (1978) - 8.075408426012638
In the Name of the Father (1993) - 8.074162542447999
The Grand Budapest Hotel (2014) - 8.073308377166766
Mr Smith Goes to Washington (1939) - 8.07107356887182
Barry Lyndon (1975) - 8.071061359435854
Le salaire de la peur (1953) - 8.070165128840992
Sherlock Jr (1924) - 8.069289204880716
Salinui chueok (2003) - 8.06863612293002
Hacksaw Ridge (2016) - 8.068607314499333
Klaus (2019) - 8.068024918087099
Relatos salvajes (2014) - 8.066180104010252
Det sjunde inseglet (1957) - 8.065700553058466
Room (2015) - 8.065328959474957
Mad Max: Fury Road (2015) - 8.062822011779913
How to Train Your Dragon (2010) - 8.061870967126781
The Big Lebowski (1998) - 8.06155186764856
Mary and Max (2009) - 8.060685002138849
Monsters, Inc (2001) - 8.059432371943146
Jaws (1975) - 8.058721201198507
Tôkyô monogatari (1953) - 8.054168007463558
Dead Poets Society (1989) - 8.054043836509118
La passion de Jeanne d'Arc (1928) - 8.05397275175545
Hotel Rwanda (2004) - 8.052092304196107
Rocky (1976) - 8.047666907270186
Ford v Ferrari (2019) - 8.04724802275274
Platoon (1986) - 8.046865595784526
Pather Panchali (1955) - 8.044333362256781
Stand by Me (1986) - 8.042066457836201
The Terminator (1984) - 8.041771430536318
Spotlight (2015) - 8.039684824111374
Rush (2013) - 8.038453997548581
Logan (2017) - 8.037356983054863
Network (1976) - 8.036776145760872
Into the Wild (2007) - 8.035454086714847
Ratatouille (2007) - 8.035238434028784
The Wizard of Oz (1939) - 8.03482314663439
Groundhog Day (1993) - 8.031886230367393
Before Sunset (2004) - 8.029774145571066
The Exorcist (1973) - 8.027889363305148
The Best Years of Our Lives (1946) - 8.026196298652872
The Incredibles (2004) - 8.0255866394864
To Be or Not to Be (1942) - 8.02436581009661
The Grapes of Wrath (1940) - 8.022714338408248
La battaglia di Algeri (1966) - 8.022541825051013
Rebecca (1940) - 8.022257033266387
Hachi: A Dog's Tale (2009) - 8.021808494079322
Cool Hand Luke (1967) - 8.021499138667165
Amores perros (2000) - 8.020940894086744
Pirates of the Caribbean: The Curse of the Black Pearl (2003) - 8.020590152993956
La haine (1995) - 8.018246115778016
Babam ve Oglum (2005) - 8.01651343490559
Les quatre cents coups (1959) - 8.016355566702194
Persona (1966) - 8.014898636604622
It Happened One Night (1934) - 8.014498200552138
The Sound of Music (1965) - 8.013025883513015
Life of Brian (1979) - 8.012994160109363
Dersu Uzala (1975) - 8.01070414804678
Ah-ga-ssi (2016) - 8.010646951611006
Jai Bhim (2021) - 8.010595607021278
Aladdin (1992) - 8.006046055210783
Gandhi (1982) - 8.00566022212702
The Help (2011) - 8.00484531384516
The Iron Giant (1999) - 8.002398691578549

In [11]:
#3
from bs4 import BeautifulSoup
import requests
import re
import pandas as pd
 
url = 'https://www.imdb.com/india/top-rated-indian-movies/'
response = requests.get(url)
soup = BeautifulSoup(response.text, "html.parser")
movies = soup.select('td.titleColumn')
ratings = [b.attrs.get('data-value')
        for b in soup.select('td.posterColumn span[name=ir]')]
 
list = []

for index in range(0, len(movies)):

    movie_string = movies[index].get_text()
    movie = (' '.join(movie_string.split()).replace('.', ''))
    movie_title = movie[len(str(index))+1:-7]
    year = re.search('\((.*?)\)', movie_string).group(1)
    place = movie[:len(str(index))-(len(movie))]
    data = {"movie_title": movie_title,
            "rating": ratings[index],
            "year": year}
    
    list.append(data)
for movie in list:
    print( movie['movie_title'], '('+movie['year'] +
        ') -', movie['rating'])

df = pd.DataFrame(list)
df.to_csv('imdb_top_100_Indian_movies.csv',index=False)

Rocketry: The Nambi Effect (2022) - 8.531125818426158
Anbe Sivam (2003) - 8.398566182541083
Golmaal (1979) - 8.389853533116192
Nayakan (1987) - 8.385657271786705
Jai Bhim (2021) - 8.383656348447946
Pariyerum Perumal (2018) - 8.374301756945059
3 Idiots (2009) - 8.350689530895226
Apur Sansar (1959) - 8.347039646932547
Manichitrathazhu (1993) - 8.328124325729888
 Kumbalangi Nights (2019) - 8.314441574568733
Black Friday (2004) - 8.31240775665593
777 Charlie (2022) - 8.302772417259717
Soorarai Pottru (2020) - 8.300356474708058
C/o Kancharapalem (2018) - 8.300334006604222
#Home (2021) - 8.299388731618969
Taare Zameen Par (2007) - 8.298835133616649
Kireedam (1989) - 8.282683507891708
Dangal (2016) - 8.282065503203743
Kaithi (2019) - 8.277637580466854
Jersey (2019) - 8.26602589842889
96 (2018) - 8.242261193916391
Asuran (2019) - 8.241502458588958
Thevar Magan (1992) - 8.236093772078396
Visaaranai (2015) - 8.23075923531464
Pather Panchali (1955) - 8.223449837930183
Thalapathi (1991) - 8.222723777350128
Sarpatta Parambarai (2021) - 8.22187416548536
Natsamrat (2016) - 8.220588124192533
Drishyam 2 (2021) - 8.210823493307105
Thani Oruvan (2015) - 8.18133653324204
Sardar Udham (2021) - 8.180090818579766
Vada Chennai (2018) - 8.178395321320018
Aparajito (1956) - 8.174343693004765
Jaane Bhi Do Yaaro (1983) - 8.17166924386902
Khosla Ka Ghosla! (2006) - 8.16657859837306
Drishyam (2013) - 8.148521306086
Chupke Chupke (1975) - 8.139777055889992
Peranbu (2018) - 8.136755293368504
Anniyan (2005) - 8.134170484455158
Agent Sai Srinivasa Athreya (2019) - 8.13393713234531
Mahanati (2018) - 8.133341584365972
Ratsasan (2018) - 8.126683492844807
Bangalore Days (2014) - 8.124736987552373
Satya (1998) - 8.123682477167321
Vikram (2022) - 8.122803033626875
Premam (2015) - 8.121649938243658
Super Deluxe (2019) - 8.121617667196093
Gangs of Wasseypur (2012) - 8.11237839659967
Devasuram (1993) - 8.109411162642434
Bhaag Milkha Bhaag (2013) - 8.106244281297835
Andhadhun (2018) - 8.103159541804965
Drishyam (2015) - 8.102837783381345
Aruvi (2016) - 8.101062930648014
Kannathil Muthamittal (2002) - 8.096164398268192
Guide (1965) - 8.094180826085605
Chithram (1988) - 8.09414096290273
Vikram Vedha (2017) - 8.09137736457852
Shahid (2012) - 8.087990526450064
Iruvar (1997) - 8.087687161927608
Zindagi Na Milegi Dobara (2011) - 8.086847679569923
Sairat (2016) - 8.086752066478121
Tumbbad (2018) - 8.084614047787158
Paan Singh Tomar (2012) - 8.08427922725025
Mudhalvan (1999) - 8.072995117701998
Chhichhore (2019) - 8.07181363646994
Spadikam (1995) - 8.06827776441889
Dhuruvangal Pathinaaru (2016) - 8.06553176040625
Swades: We, the People (2004) - 8.064585253972917
Chak De! India (2007) - 8.064215234175496
Black (2005) - 8.063029550424577
Jo Jeeta Wohi Sikandar (1992) - 8.060331176440162
Pudhu Pettai (2006) - 8.057696365704476
Mandela (2021) - 8.05626312487261
Papanasam (2015) - 8.055740570095402
Pyaasa (1957) - 8.055465631041994
Munna Bhai MBBS (2003) - 8.05429985472588
Uri: The Surgical Strike (2019) - 8.054063590251122
Article 15 (2019) - 8.049525985016905
Queen (2013) - 8.047944269538277
Soodhu Kavvum (2013) - 8.047692998259011
Kaakkaa Muttai (2014) - 8.04555516975722
Talvar (2015) - 8.045160141199712
Lagaan: Once Upon a Time in India (2001) - 8.044260803084992
PK (2014) - 8.043479334669737
OMG: Oh My God! (2012) - 8.039715059961486
Jigarthanda (2014) - 8.037142670008647
Sarfarosh (1999) - 8.0337315595982
Hera Pheri (2000) - 8.03096451882768
Udaan (2010) - 8.030375912653492
Barfi! (2012) - 8.03024334136444
Theeran Adhigaaram Ondru (2017) - 8.029784722987866
Sholay (1975) - 8.029168694468904
Ustad Hotel (2012) - 8.025603645393412
The Legend of Bhagat Singh (2002) - 8.020814062941527
Angoor (1982) - 8.013766421631066
Rang De Basanti (2006) - 8.013556265070868
Baahubali 2: The Conclusion (2017) - 8.011692633952151
Baasha (1995) - 8.010471734073068
Masaan (2015) - 8.007393407396766
 Virumandi (2004) - 8.006979835442634
Kahaani (2012) - 8.00602653451128
Maheshinte Prathikaaram (2016) - 8.004864470548362
Dil Chahta Hai (2001) - 8.004470352045159
A Wednesday (2008) - 8.001097123133828
Roja (1992) - 7.9987704672047535
Kaun Pravin Tambe? (2022) - 7.99842369293806
Iqbal (2005) - 7.995922145998166
Nil Battey Sannata (2015) - 7.994412101611517
Pink (2016) - 7.994368411365118
Pithamagan (2003) - 7.994132612038156
Shershaah (2021) - 7.992946904807046
Lage Raho Munna Bhai (2006) - 7.9929282572806395
Jana Gana Mana (2022) - 7.990913182961183
Charulata (1964) - 7.979211225352386
Anand (1971) - 7.978256552584972
Section 375 (2019) - 7.97306941506501
Alai Payuthey (2000) - 7.971512939861667
Bajrangi Bhaijaan (2015) - 7.96792032736498
Omkara (2006) - 7.966236076335729
Lucia (2013) - 7.962056988244785
Bombay (1995) - 7.9599321683350786
Oru Vadakkan Veeragatha (1989) - 7.9575589625876955
Bommarillu (2006) - 7.955044103533019
KGF: Chapter 1 (2018) - 7.949231272554262
Indian (1996) - 7.948715191379358
KGF: Chapter 2 (2022) - 7.943779644541718
The Great Indian Kitchen (2021) - 7.943472885006541
Rangasthalam (2018) - 7.940151715254639
Haider (2014) - 7.939012329042971
Dilwale Dulhania Le Jayenge (1995) - 7.933832242231305
Mughal-E-Azam (1960) - 7.932578962269426
Special Chabbis (2013) - 7.920280238006166
Athadu (2005) - 7.918907225702506
Maqbool (2003) - 7.91781972350755
Andaz Apna Apna (1994) - 7.917649470898359
Maanaadu (2021) - 7.916597342429828
Thadam (2019) - 7.916416080463812
Padayappa (1999) - 7.910129787614661
Vaaranam Aayiram (2008) - 7.90795246666896
Android Kunjappan Version 525 (2019) - 7.907143224243234
Pelli Choopulu (2016) - 7.907075435327994
Gulaal (2009) - 7.903497432531474
Naduvula Konjam Pakkatha Kaanom (2012) - 7.880522547272479
Ugly (2013) - 7.878917442653672
Vaastav: The Reality (1999) - 7.8785052619840075
Badhaai ho (2018) - 7.877669751305072
Deewaar (1975) - 7.877143429255314
Gully Boy (2019) - 7.876317345147896
Ulidavaru Kandanthe (2014) - 7.874397241714133
Company (2002) - 7.873903553006122
Evaru (2019) - 7.873836681099556
Kshanam (2016) - 7.870674843257041
Padosan (1968) - 7.8658521160884955
Maanagaram (2017) - 7.865453695451
Aadukalam (2011) - 7.864937041490518
Major (2022) - 7.864221934923289
Nayattu (2021) - 7.860760580854397
Thondimuthalum Dhriksakshiyum (2017) - 7.854988688671997
DevD (2009) - 7.853661301506499
My Name Is Khan (2010) - 7.851254914486604
Karthikeya 2 (2022) - 7.8457032454293145
Pranchiyettan and the Saint (2010) - 7.842897917082236
Take Off (2017) - 7.840371057450457
Kal Ho Naa Ho (2003) - 7.836846792573929
Baishe Srabon (2011) - 7.836228829508345
Jab We Met (2007) - 7.831157166819415
Ayyappanum Koshiyum (2020) - 7.829727601254992
Arjun Reddy (2017) - 7.827198083235138
Manjhi: The Mountain Man (2015) - 7.8256991066299415
Super 30 (2019) - 7.824042254665281
Dil Bechara (2020) - 7.822279065763532
Mukkabaaz (2017) - 7.8218924636358125
Border (1997) - 7.818479312058142
Deiva Thirumagal (2011) - 7.814169132259073
Ship of Theseus (2012) - 7.81399996369717
Karnan (2021) - 7.811091857866317
Charlie (2015) - 7.8110197051455375
Vedam (2010) - 7.807456231253951
Padman (2018) - 7.806198965402387
Salaam Bombay! (1988) - 7.80579804301378
Bãhubali: The Beginning (2015) - 7.805048493915339
Jalsaghar (1958) - 7.801607165461609
Ankhon Dekhi (2013) - 7.795411095478072
RRR (Rise Roar Revolt) (Rise Roar Revolt) - 7.7950879481311155
Baby (2015) - 7.7915031373247885
Vinnaithaandi Varuvaayaa (2010) - 7.783699149810908
MS Dhoni: The Untold Story (2016) - 7.782968019689832
Malik (2021) - 7.782793215835217
Pizza (2012) - 7.781968777751144
Kirik Party (2016) - 7.778956261614323
Hindi Medium (2017) - 7.773706743322021
English Vinglish (2012) - 7.771703812268703
Memories (2013) - 7.77123826622411
Lakshya (2004) - 7.770250834412828
Airlift (2016) - 7.768314758688285
Dor (2006) - 7.767374657012228
Hey Ram (2000) - 7.7672936274192965
Johnny Gaddaar (2007) - 7.766610535855641
The Tashkent Files (2019) - 7.764361040679801
Joseph (2018) - 7.763163426623482
Sita Ramam (2022) - 7.760691882106464
KaakhaKaakha: The Police (2003) - 7.756804026467247
Hridayam (2022) - 7.756648364607432
Gangaajal (2003) - 7.748066239763253
Anjaam Pathiraa (2020) - 7.740456622612925
Vettaiyaadu Vilaiyaadu (2006) - 7.735927088440486
The Lunchbox (2013) - 7.730088224221679
Mumbai Police (2013) - 7.7287076558935945
Ab Tak Chhappan (2004) - 7.727111356342909
Okkadu (2003) - 7.723398609906263
Pokiri (2006) - 7.719744190303029
Unnaipol Oruvan (2009) - 7.7177692183893125
Thuppakki (2012) - 7.7160287095607245
Angamaly Diaries (2017) - 7.715762216455563
Oopiri (2016) - 7.713034423199892
Manam (2014) - 7.710364844105231
Secret Superstar (2017) - 7.707048795090961
Vicky Donor (2012) - 7.705469278250747
Ghilli (2004) - 7.705056364047265
Mother India (1957) - 7.700902314927876
Veer-Zaara (2004) - 7.698679610277896
RangiTaranga (2015) - 7.696395370904595
Kaththi (2014) - 7.69538042883287
Mimi (2021) - 7.693972664651565
Stanley Ka Dabba (2011) - 7.69363287873895
Rock On!! (2008) - 7.6931096509859485
Udta Punjab (2016) - 7.692917348110826
Nayak: The Real Hero (2001) - 7.692353679069302
Mr India (1987) - 7.691976832082775
Oru CBI Diary Kurippu (1988) - 7.691424375567701
Dia (2020) - 7.688871300331051
Sonchiriya (2019) - 7.687009907027705
Badla (2019) - 7.684798052390757
Happy Days (2007) - 7.684647913416391
Thulladha Manamum Thullum (1999) - 7.684069543910226
Raazi (2018) - 7.6826398757316054
Minnal Murali (2021) - 7.68217657918878
Dasvidaniya (2008) - 7.677957234653004
Aayirathil Oruvan (2010) - 7.677359312386423
Kai po che! (2013) - 7.671489976823412
Poove Unakkaga (1996) - 7.671016944712788
Joji (2021) - 7.663752245339471
Goodachari (2018) - 7.659989538315476
Ko (2011) - 7.648076672818833
Don (1978) - 7.6475861040009425
Ennu Ninte Moideen (2015) - 7.643346624037252
Aligarh (2015) - 7.642419556981472
Velaiilla Pattadhari (2014) - 7.640246141169842
Guru (2007) - 7.640171637692868
24 (2016) - 7.637821786833572

In [26]:
#4
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = "https://presidentofindia.nic.in/former-presidents.htm"

page = requests.get(url)
bs = BeautifulSoup(page.content, "html.parser")
nameList = bs.findAll(["h3"])
termofoffice = bs.findAll('span', class_="terms")
for name in nameList:
    print(name.get_text())

Shri Ram Nath Kovind (birth - 1945)
Shri Pranab Mukherjee (1935-2020)
Smt Pratibha Devisingh Patil (birth - 1934)
DR. A.P.J. Abdul Kalam (1931-2015)
Shri K. R. Narayanan (1920 - 2005)
Dr Shankar Dayal Sharma (1918-1999)
Shri R Venkataraman (1910-2009)
Giani Zail Singh (1916-1994)
Shri Neelam Sanjiva Reddy (1913-1996)
Dr. Fakhruddin Ali Ahmed (1905-1977)
Shri Varahagiri Venkata Giri (1894-1980)
Dr. Zakir Husain (1897-1969)
Dr. Sarvepalli Radhakrishnan (1888-1975)
Dr. Rajendra Prasad (1884-1963)

In [20]:
#5a
from bs4 import BeautifulSoup
import requests
import pandas as pd
url = ('https://www.icc-cricket.com/rankings/mens/team-rankings/odi')
response = requests.get(url)

soup = BeautifulSoup (response.text,"html.parser")
na = soup.find_all('table',class_='table')

team=[]
for i in na:
    for k in i.find_all('span',class_='u-hide-phablet'):
        team.append(k.text.replace('\n',''))
        m=soup.find_all('tr',class_='table-body')
        
        ma=[]
for i in m:
    for j in i.find('td',class_='table-body__cell u-center-text'):
        ma.append(j)
        
       
    z=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-center-text'):
        z.append(j.text.split('\n'))    
        
p=z[1::2]
g=[]
for i in p:
    g.extend(i)


r=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-text-right rating'):
        r.append(j.text)
m=[soup.find('td',class_='rankings-block__banner--matches').text]    
ps=[soup.find('td',class_='rankings-block__banner--points').text]
q=[soup.find('td',class_='rankings-block__banner--rating u-text-right').text.strip()]



mat=m+ma
pt=ps+g
ra=q+r


Men_team=pd.DataFrame({},index=range(1,21))
Men_team["TEAM"]=team
Men_team["MATCHES"]=mat
Men_team["POINTS"]=pt
Men_team["RATING"]=ra


Men_team[0:10]

            TEAM MATCHES POINTS RATING
1    New Zealand      19  2,355    124
2        England      27  3,226    119
3          India      31  3,447    111
4       Pakistan      22  2,354    107
5      Australia      23  2,325    101
6   South Africa      21  2,111    101
7     Bangladesh      30  2,753     92
8      Sri Lanka      29  2,658     92
9    West Indies      41  2,902     71
10   Afghanistan      18  1,238     69

In [21]:
#5b
page=requests.get("https://www.icc-cricket.com/rankings/mens/player-rankings/odi")

soup=BeautifulSoup(page.content)

name1=[soup.find('div',class_='rankings-block__banner--name').text]  
name2=soup.find_all('td',class_='table-body__cell name') 

n2=[]
for i in name2:
    for j in i.find('a'):
        n2.append(j)

name=name1+n2


t=[soup.find('div',class_='rankings-block__banner--nationality')]
t1=t[0].get_text().split()
t1
team1=[t1[0]]   
rating1=[t1[1]] 


tn=soup.find_all('td',class_='table-body__cell nationality-logo')


t2=[]
for i in tn:
    for j in i.find_all('span',class_='table-body__logo-text'):
        t2.append(j.text)
        

team_name=team1+t2

ra=soup.find_all('td',class_='table-body__cell u-text-right rating')


r2=[]
for i in ra:
    r2.append(i.text)
    
   
 rating=rating1+r2


top_10_Batsmen=pd.DataFrame({'Batsmen Name':name,'Country':team_name,'Rating':rating},index=range(1,56))


top_10_Batsmen[:10]

             Batsmen Name Country Rating
1              Babar Azam     PAK    890
2   Rassie van der Dussen      SA    789
3         Quinton de Kock      SA    784
4             Imam-ul-Haq     PAK    779
5             Virat Kohli     IND    744
6            Rohit Sharma     IND    740
7            David Warner     AUS    737
8          Jonny Bairstow     ENG    732
9             Ross Taylor      NZ    722
10            Aaron Finch     AUS    715

In [22]:
#5c 
page=requests.get('https://www.icc-cricket.com/rankings/mens/player-rankings/odi')
soup=BeautifulSoup(page.content)


name1=soup.find_all('td',class_='table-body__cell name')
name_1=[]
for i in name1:
    for j in i.find('a'):
        name_1.append(j)  
all_name1=name_1[-9:]


team=soup.find_all('td',class_='table-body__cell nationality-logo')
team_1=[]
for i in team:
    for j in i.find_all('span',class_='table-body__logo-text'):
        team_1.append(j.text)        
team_name1=team_1[-9:]



rating=soup.find_all('td',class_='table-body__cell u-text-right rating')
rating_1=[]
for i in rating:
    rating_1.append(i.text)    
rating1=rating_1[-9:]


all_name2=['Trent Boult']
team_name2=['NZ']
rating2=['720']

player_name=all_name2+all_name1
team_name=team_name2+team_name1
rating=rating2+rating1

mens_bowlers=pd.DataFrame({'Player Name':player_name,'Player Team':team_name,'Player Rating':rating},index=range(1,11))

mens_bowlers

            Player Name Player Team Player Rating
1           Trent Boult          NZ           720
2         Mohammad Nabi         AFG           325
3           Rashid Khan         AFG           290
4         Sikandar Raza         ZIM           280
5      Mitchell Santner          NZ           275
6       Zeeshan Maqsood         OMA           238
7          Mehedi Hasan         BAN           238
8          Chris Woakes         ENG           235
9   Colin de Grandhomme          NZ           227
10        Glenn Maxwell         AUS           222

In [23]:
#6a

url1="https://www.icc-cricket.com/rankings/womens/team-rankings/odi"

r=requests.get(url1)

soup=BeautifulSoup(r.content,"html.parser")

na=soup.find_all('table',class_='table')

team=[]
for i in na:
    for k in i.find_all('span',class_='u-hide-phablet'):
        team.append(k.text.replace('\n',''))
        
      
    m=soup.find_all('tr',class_='table-body')


ma=[]
for i in m:
    for j in i.find('td',class_='table-body__cell u-center-text'):
        ma.append(j)
        
      
    z=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-center-text'):
        z.append(j.text.split('\n'))    
        
p=z[1::2]
g=[]
for i in p:
    g.extend(i)

#pars rating
r=[]
for i in m:
    for j in i.find_all('td',class_='table-body__cell u-text-right rating'):
        r.append(j.text)
    
    
    
m=[soup.find('td',class_='rankings-block__banner--matches').text]
ps=[soup.find('td',class_='rankings-block__banner--points').text]
q=[soup.find('td',class_='rankings-block__banner--rating u-text-right').text.strip()]


mat=m+ma
pt=ps+g
ra=q+r


WoMen_team=pd.DataFrame({},index=range(1,12))
WoMen_team["TEAM"]=team
WoMen_team["MATCHES"]=mat
WoMen_team["POINTS"]=pt
WoMen_team["RATING"]=ra


WoMen_team[0:10]

            TEAM MATCHES POINTS RATING
1      Australia      29  4,837    167
2        England      33  4,046    123
3   South Africa      35  4,157    119
4          India      32  3,219    101
5    New Zealand      31  3,019     97
6    West Indies      30  2,768     92
7     Bangladesh      12    930     78
8       Pakistan      30  1,962     65
9        Ireland       9    405     45
10     Sri Lanka      11    495     45

In [24]:
#6b

page=requests.get("https://www.icc-cricket.com/rankings/womens/player-rankings/odi")

soup=BeautifulSoup(page.content)


name1=[soup.find('div',class_='rankings-block__banner--name').text]  
name2=soup.find_all('td',class_='table-body__cell name')  

n2=[]
for i in name2:
    for j in i.find('a'):
        n2.append(j)

name=name1+n2



t=[soup.find('div',class_='rankings-block__banner--nationality')]
t1=t[0].get_text().split()
t1
team1=[t1[0]]   
rating1=[t1[1]] 

tn=soup.find_all('td',class_='table-body__cell nationality-logo')

t2=[]
for i in tn:
    for j in i.find_all('span',class_='table-body__logo-text'):
        t2.append(j.text)
        

team_name=team1+t2


ra=soup.find_all('td',class_='table-body__cell u-text-right rating')


r2=[]
for i in ra:
    r2.append(i.text)
    

rating=rating1+r2


top_10_Batsmen=pd.DataFrame({'Batsmen Name':name[0:10],'Country':team_name[0:10],'Rating':rating[0:10]},index=range(1,11))


top_10_Batsmen[:10]

           Batsmen Name Country Rating
1          Alyssa Healy     AUS    785
2           Beth Mooney     AUS    749
3        Natalie Sciver     ENG    747
4       Laura Wolvaardt      SA    732
5           Meg Lanning     AUS    710
6        Rachael Haynes     AUS    701
7     Amy Satterthwaite      NZ    681
8        Tammy Beaumont     ENG    667
9   Chamari Athapaththu      SL    655
10      Smriti Mandhana     IND    649

In [25]:
#6c

page=requests.get('https://www.icc-cricket.com/rankings/womens/player-rankings/odi')
soup=BeautifulSoup(page.content)


name1=soup.find_all('td',class_='table-body__cell name')
name_1=[]
for i in name1:
    for j in i.find('a'):
        name_1.append(j)  
all_name1=name_1[-9:]




team=soup.find_all('td',class_='table-body__cell nationality-logo')
team_1=[]
for i in team:
    for j in i.find_all('span',class_='table-body__logo-text'):
        team_1.append(j.text)        
team_name1=team_1[-9:]




rating=soup.find_all('td',class_='table-body__cell u-text-right rating')
rating_1=[]
for i in rating:
    rating_1.append(i.text)    
rating1=rating_1[-9:]



all_name2=['Natalie sciver']
team_name2=['ENG']
rating2=['379']


player_name=all_name2+all_name1
team_name=team_name2+team_name1
rating=rating2+rating1


Women_all_rounder=pd.DataFrame({'Player Name':player_name,'Player Team':team_name,'Player Rating':rating},index=range(1,11))

Women_all_rounder

         Player Name Player Team Player Rating
1     Natalie sciver         ENG           379
2       Ellyse Perry         AUS           374
3     Marizanne Kapp          SA           349
4    Hayley Matthews          WI           339
5        Amelia Kerr          NZ           336
6   Ashleigh Gardner         AUS           270
7      Deepti Sharma         IND           252
8      Jess Jonassen         AUS           246
9    Katherine Brunt         ENG           220
10   Stafanie Taylor          WI           207

In [1]:
#7
from bs4 import BeautifulSoup
import requests
import pandas as pd

url = 'https://www.cnbc.com/world/?region=world'

page = requests.get(url)
page

soup = BeautifulSoup(page.content, "html.parser")

headline = soup.find('div', class_='RiverHeadline-headline RiverHeadline-hasThumbnail')
headline.text

headline = []

for i in soup.find_all('div', class_="RiverHeadline-headline RiverHeadline-hasThumbnail"):
    headline.append(i.text)
headline

paper_url = []
for link in soup.findAll("a"):
    if 'href' in link.attrs:
        print(link.attrs['href'])

#MainContent
//www.cnbc.com/world/
/
/markets/
/pre-markets/
/us-markets/
/markets-europe/
/china-markets/
/markets-asia-pacific/
/world-markets/
/currencies/
/cryptocurrency/
/futures-and-commodities/
/bonds/
/funds-and-etfs/
/business/
/economy/
/finance/
/health-and-science/
/media/
/real-estate/
/energy/
/climate/
/transportation/
/industrials/
/retail/
/wealth/
/life/
/small-business/
/investing/
/personal-finance/
/fintech/
/financial-advisors/
/options-action/
/etf-street/
https://buffett.cnbc.com
/earnings/
/trader-talk/
/technology/
/cybersecurity/
/enterprise/
/internet/
/media/
/mobile/
/social-media/
/cnbc-disruptors/
/tech-guide/
/politics/
/white-house/
/policy/
/defense/
/congress/
/equity-opportunity/
/europe-politics/
/china-politics/
/asia-politics/
/world-politics/
/tv/
/live-audio/
/latest-video/
/top-video/
/video-ceo-interviews/
/europe-television/
/asia-business-day/
/podcast/
/digital-original/
/watchlist/
/investingclub/
/investingclub/cramer-trade-alert/
/investingclub/cramers-morning-thoughts/
/investingclub/analysis/
/investingclub/morning-meeting/
/investingclub/charitable-trust/
/pro/
/pro/news/
/pro/
#
#
/make-it/
/?region=usa
/world/
/watchlist/
#
#
/
/markets/
/business/
/investing/
/technology/
/politics/
/tv/
/watchlist/
/investingclub/
/pro/
#
#
#
#
#
https://www.cnbc.com/2022/08/26/europe-markets-open-to-close-powells-jackson-hole-speech-in-focus.html
https://www.cnbc.com/2022/08/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/quotes/US10Y
https://www.cnbc.com/2022/08/25/cramer-says-theres-a-bull-market-in-these-4-industries-here-are-his-favorite-stocks-in-them.html
https://www.cnbc.com/2022/08/25/china-ev-maker-xpeng-to-launch-a-tesla-model-y-competitor-in-2023.html
https://www.cnbc.com/2022/08/25/jim-cramer-what-4-convoluted-ceo-jargon-terms-mean-for-investors.html
https://www.cnbc.com/2022/08/25/cost-of-living-brits-to-ditch-home-working-as-heating-bills-soar.html
https://www.cnbc.com/2022/08/26/uk-energy-bills-to-rise-by-80percent-in-october-as-regulator-announces-hike.html
https://www.cnbc.com/2022/08/26/uk-energy-bills-to-rise-by-80percent-in-october-as-regulator-announces-hike.html
https://www.cnbc.com/2022/08/26/europe-markets-open-to-close-powells-jackson-hole-speech-in-focus.html
/pro/
https://www.cnbc.com/2022/08/26/fund-manager-2-stocks-to-navigate-higher-for-longer-inflation.html
https://www.cnbc.com/2022/08/25/powell-isnt-likely-to-tell-investors-what-they-want-to-hear-friday.html
https://www.cnbc.com/2022/08/25/powell-isnt-likely-to-tell-investors-what-they-want-to-hear-friday.html
https://www.cnbc.com/2022/08/26/tomato-flu-indian-health-advisory-for-rare-virus-infecting-children.html
https://www.cnbc.com/2022/08/26/tomato-flu-indian-health-advisory-for-rare-virus-infecting-children.html
/pro/
https://www.cnbc.com/2022/08/26/these-drugmakers-could-rally-more-than-40percent-amid-new-developments-in-zantac-lawsuit-citi-says.html
https://www.cnbc.com/2022/08/26/us-bonds-treasury-yields-move-higher-ahead-of-powell-speech-.html
https://www.cnbc.com/2022/08/26/russia-ukraine-live-updates.html
https://www.cnbc.com/2022/08/26/whartons-jeremy-siegel-on-fed-rate-hike-ahead-of-jackson-hole.html
https://www.cnbc.com/2022/08/26/china-pumping-billions-to-infrastructure-but-commodity-markets-muted.html
https://www.cnbc.com/2022/08/26/uk-energy-bills-to-rise-by-80percent-in-october-as-regulator-announces-hike.html
https://www.cnbc.com/2022/08/26/europe-markets-open-to-close-powells-jackson-hole-speech-in-focus.html
https://www.cnbc.com/2022/08/26/parenting-tips-randi-zuckerberg-on-kids-and-the-metaverse-screen-time.html
https://www.cnbc.com/2022/08/26/tomato-flu-indian-health-advisory-for-rare-virus-infecting-children.html
https://www.cnbc.com/2022/08/26/crypto-winter-is-coming-but-it-will-be-a-warm-winter-says-vc-firm.html
https://www.cnbc.com/2022/08/26/companies-are-pulling-back-on-hiring-amid-recession-fears-mercer.html
/pro/
https://www.cnbc.com/2022/08/26/tech-investor-paul-meeks-chip-stock-he-wouldnt-buy-even-on-the-dip.html
https://www.cnbc.com/2022/08/25/spacex-and-t-mobile-team-up-to-use-starlink-satellites.html
/pro/
https://www.cnbc.com/2022/08/26/fund-manager-2-stocks-to-navigate-higher-for-longer-inflation.html
https://www.cnbc.com/2022/08/26/japan-is-pivoting-to-more-nuclear-power-the-iea-says-its-good-news.html
https://www.cnbc.com/2022/08/26/asia-markets-jackson-hole-stocks-economic-data-interest-rates.html
https://www.cnbc.com/2022/08/26/how-to-find-cheap-hotel-rooms-survey-compares-popular-website-rates.html
https://www.cnbc.com/2022/08/26/bitcoin-btc-price-key-metric-flashes-bottom-for-the-crypto.html
https://www.cnbc.com/2022/08/25/chipotle-restaurant-in-michigan-votes-to-unionize-in-a-first-for-the-chain.html
/investingclub/
https://www.cnbc.com/2022/08/25/marvells-warning-of-a-soft-third-quarter-is-just-a-hiccup-.html
https://www.cnbc.com/2022/08/25/cramers-lightning-round-i-prefer-mcdonalds-over-kfc-parent-yum-brands.html
https://www.cnbc.com/2022/08/25/workday-shares-surge-after-earnings-beat-co-ceo-says-deals-are-still-closing.html
https://www.cnbc.com/2022/08/25/jim-cramer-what-4-convoluted-ceo-jargon-terms-mean-for-investors.html
https://www.cnbc.com/2022/08/25/williams-sonoma-will-soon-launch-a-collaboration-with-roblox-says-the-home-retailers-ceo.html
https://www.cnbc.com/2022/08/25/cramer-says-theres-a-bull-market-in-these-4-industries-here-are-his-favorite-stocks-in-them.html
https://www.cnbc.com/2022/08/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/2022/08/25/should-you-request-a-refund-on-student-loan-payments-made-during-pause.html
/pro/
https://www.cnbc.com/2022/08/25/cnbc-in-5-minutes-all-the-buy-sell-and-hold-stock-calls-from-thursday.html
https://www.cnbc.com/2022/08/25/stocks-making-biggest-after-hour-moves-ulta-affirm-marvell-and-more.html
https://www.cnbc.com/2022/08/25/meta-to-debut-new-vr-headset-in-october-zuckerberg-tells-rogan.html
/us-market-movers/
https://www.cnbc.com/2022/08/26/china-pumping-billions-to-infrastructure-but-commodity-markets-muted.html
https://www.cnbc.com/su-lin-tan/
https://www.cnbc.com/2022/08/26/china-pumping-billions-to-infrastructure-but-commodity-markets-muted.html
https://www.cnbc.com/su-lin-tan/
/pro/
https://www.cnbc.com/2022/08/26/tech-investor-paul-meeks-chip-stock-he-wouldnt-buy-even-on-the-dip.html
https://www.cnbc.com/zavier-ong/
https://www.cnbc.com/2022/08/26/tech-investor-paul-meeks-chip-stock-he-wouldnt-buy-even-on-the-dip.html
https://www.cnbc.com/zavier-ong/
https://www.cnbc.com/2022/08/26/bitcoin-btc-price-key-metric-flashes-bottom-for-the-crypto.html
https://www.cnbc.com/arjun-kharpal/
https://www.cnbc.com/2022/08/26/bitcoin-btc-price-key-metric-flashes-bottom-for-the-crypto.html
https://www.cnbc.com/arjun-kharpal/
https://www.cnbc.com/2022/08/26/russia-ukraine-live-updates.html
https://www.cnbc.com/sam-meredith/
https://www.cnbc.com/2022/08/26/russia-ukraine-live-updates.html
https://www.cnbc.com/sam-meredith/
https://www.cnbc.com/2022/08/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/tanaya-macheel/
https://www.cnbc.com/2022/08/25/stock-market-futures-open-to-close-news.html
https://www.cnbc.com/tanaya-macheel/
https://www.cnbc.com/2022/08/26/whartons-jeremy-siegel-on-fed-rate-hike-ahead-of-jackson-hole.html
https://www.cnbc.com/jihye-lee/
https://www.cnbc.com/2022/08/26/whartons-jeremy-siegel-on-fed-rate-hike-ahead-of-jackson-hole.html
https://www.cnbc.com/jihye-lee/
https://www.cnbc.com/video/2022/08/26/career-advice-take-at-least-one-risk-per-day-ceo-says.html
https://www.cnbc.com/2022/08/26/how-to-find-cheap-hotel-rooms-survey-compares-popular-website-rates.html
https://www.cnbc.com/2022/08/26/how-to-find-cheap-hotel-rooms-survey-compares-popular-website-rates.html
https://www.cnbc.com/2022/08/25/tiktok-creators-are-calling-out-businesses-on-shrinkflation-.html
https://www.cnbc.com/2022/08/25/tiktok-creators-are-calling-out-businesses-on-shrinkflation-.html
https://www.cnbc.com/2022/08/25/dont-buy-a-new-iphone-or-apple-watch-right-now.html
https://www.cnbc.com/todd-haselton/
https://www.cnbc.com/2022/08/25/dont-buy-a-new-iphone-or-apple-watch-right-now.html
https://www.cnbc.com/todd-haselton/
https://www.cnbc.com/2022/08/26/parenting-tips-randi-zuckerberg-on-kids-and-the-metaverse-screen-time.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/26/parenting-tips-randi-zuckerberg-on-kids-and-the-metaverse-screen-time.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/26/audi-confirms-formula-1-entry-from-2026-as-sport-welcomes-volkswagen-brand.html
https://www.cnbc.com/2022/08/26/audi-confirms-formula-1-entry-from-2026-as-sport-welcomes-volkswagen-brand.html
https://www.cnbc.com/2022/08/26/japan-is-pivoting-to-more-nuclear-power-the-iea-says-its-good-news.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/2022/08/26/japan-is-pivoting-to-more-nuclear-power-the-iea-says-its-good-news.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/2022/08/26/crypto-winter-is-coming-but-it-will-be-a-warm-winter-says-vc-firm.html
https://www.cnbc.com/natalie-tham/
https://www.cnbc.com/2022/08/26/crypto-winter-is-coming-but-it-will-be-a-warm-winter-says-vc-firm.html
https://www.cnbc.com/natalie-tham/
https://www.cnbc.com/2022/08/26/asia-markets-jackson-hole-stocks-economic-data-interest-rates.html
https://www.cnbc.com/abigail-ng/
https://www.cnbc.com/2022/08/26/asia-markets-jackson-hole-stocks-economic-data-interest-rates.html
https://www.cnbc.com/abigail-ng/
https://www.cnbc.com/2022/08/25/qantas-ceo-blames-little-government-help-and-covid-for-lagging-peers.html
https://www.cnbc.com/su-lin-tan/
https://www.cnbc.com/2022/08/25/qantas-ceo-blames-little-government-help-and-covid-for-lagging-peers.html
https://www.cnbc.com/su-lin-tan/
https://www.cnbc.com/2022/08/25/tesla-threatens-to-sue-critic-over-ads-showing-cars-hitting-mannequins.html
https://www.cnbc.com/lora-kolodny/
https://www.cnbc.com/2022/08/25/tesla-threatens-to-sue-critic-over-ads-showing-cars-hitting-mannequins.html
https://www.cnbc.com/lora-kolodny/
https://www.cnbc.com/2022/08/26/companies-are-pulling-back-on-hiring-amid-recession-fears-mercer.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/26/companies-are-pulling-back-on-hiring-amid-recession-fears-mercer.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/25/spacex-and-t-mobile-team-up-to-use-starlink-satellites.html
https://www.cnbc.com/lora-kolodny/
https://www.cnbc.com/2022/08/25/spacex-and-t-mobile-team-up-to-use-starlink-satellites.html
https://www.cnbc.com/lora-kolodny/
https://www.cnbc.com/2022/08/25/sony-raises-price-of-playstation-5-console-due-to-soaring-inflation.html
https://www.cnbc.com/arjun-kharpal/
https://www.cnbc.com/2022/08/25/sony-raises-price-of-playstation-5-console-due-to-soaring-inflation.html
https://www.cnbc.com/arjun-kharpal/
//www.cnbc.com/us-market-movers/
/us-market-movers/
/stocks/
https://www.cnbc.com/2022/08/26/us-bonds-treasury-yields-move-higher-ahead-of-powell-speech-.html
https://www.cnbc.com/jenni-reid/
https://www.cnbc.com/2022/08/25/stocks-making-biggest-after-hour-moves-ulta-affirm-marvell-and-more.html
https://www.cnbc.com/tanaya-macheel/
https://www.cnbc.com/2022/08/25/earnings-shocks-arent-blowing-up-sectors-here-are-verdicts-investors-might-draw.html
/pro/
https://www.cnbc.com/michael-santoli/
https://www.cnbc.com/2022/08/24/us-stock-futures-flat-after-dow-sp-500-break-three-day-slide-.html
https://www.cnbc.com/sarah-min/
https://www.cnbc.com/carmen-reinicke/
//www.cnbc.com/live-tv/
//www.cnbc.com/latest-video/
https://www.cnbc.com/video/2022/08/19/how-chinas-covid-shutdowns-keep-hitting-global-supply-chains.html
https://www.cnbc.com/video/2022/08/20/why-rent-in-nyc-is-out-of-control-right-now.html
https://www.cnbc.com/video/2022/08/25/jim-cramer-says-these-4-industries-are-in-definite-bull-market-mode-so-look-to-buy-these-stocks.html
https://www.cnbc.com/special-reports/
https://www.cnbc.com/2022/08/23/i-make-119000-a-month-in-passive-income-here-are-businesses-you-can-start-for-99-dollars-or-less.html
https://www.cnbc.com/2022/08/25/dont-buy-a-new-iphone-or-apple-watch-right-now.html
https://www.cnbc.com/2022/08/24/sadhguru-has-a-message-for-people-desperate-for-a-luxury-lifestyle.html
https://www.cnbc.com/2022/08/26/uk-energy-bills-to-rise-by-80percent-in-october-as-regulator-announces-hike.html
https://www.cnbc.com/2022/08/25/powell-isnt-likely-to-tell-investors-what-they-want-to-hear-friday.html
https://www.cnbc.com/pro/news/
https://www.cnbc.com/2022/08/26/these-drugmakers-could-rally-more-than-40percent-amid-new-developments-in-zantac-lawsuit-citi-says.html
https://www.cnbc.com/2022/08/26/these-drugmakers-could-rally-more-than-40percent-amid-new-developments-in-zantac-lawsuit-citi-says.html
/pro/
https://www.cnbc.com/samantha-subin/
https://www.cnbc.com/2022/08/26/tech-investor-paul-meeks-chip-stock-he-wouldnt-buy-even-on-the-dip.html
https://www.cnbc.com/2022/08/26/tech-investor-paul-meeks-chip-stock-he-wouldnt-buy-even-on-the-dip.html
/pro/
https://www.cnbc.com/zavier-ong/
https://www.cnbc.com/2022/08/26/fund-manager-2-stocks-to-navigate-higher-for-longer-inflation.html
https://www.cnbc.com/2022/08/26/fund-manager-2-stocks-to-navigate-higher-for-longer-inflation.html
/pro/
https://www.cnbc.com/zavier-ong/
https://www.cnbc.com/2022/08/25/cnbc-in-5-minutes-all-the-buy-sell-and-hold-stock-calls-from-thursday.html
https://www.cnbc.com/2022/08/25/cnbc-in-5-minutes-all-the-buy-sell-and-hold-stock-calls-from-thursday.html
/pro/
https://www.cnbc.com/christina-falso/
https://www.cnbc.com/2022/08/25/-ibm-spinoff-kyndryl-is-now-one-of-david-einhorns-biggest-technology-bets.html
https://www.cnbc.com/2022/08/25/-ibm-spinoff-kyndryl-is-now-one-of-david-einhorns-biggest-technology-bets.html
/pro/
https://www.cnbc.com/yun-li/
https://www.cnbc.com/sustainable-future/
https://www.cnbc.com/2022/08/17/london-to-face-water-restrictions-from-next-week-thames-water-says-.html
https://www.cnbc.com/2022/08/17/london-to-face-water-restrictions-from-next-week-thames-water-says-.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/video/2022/08/18/meet-the-indian-guru-who-is-on-a-mission-to-reverse-soil-degradation.html
https://www.cnbc.com/video/2022/08/18/meet-the-indian-guru-who-is-on-a-mission-to-reverse-soil-degradation.html
https://www.cnbc.com/dan-murphy/
https://www.cnbc.com/video/2022/08/18/sadhguru-on-the-meaning-of-life-athere-is-no-meaning-to-anythinga.html
https://www.cnbc.com/video/2022/08/18/sadhguru-on-the-meaning-of-life-athere-is-no-meaning-to-anythinga.html
https://www.cnbc.com/dan-murphy/
https://www.cnbc.com/2022/08/03/climate-change-isnt-a-left-wing-plot-charity-founder-says.html
https://www.cnbc.com/2022/08/03/climate-change-isnt-a-left-wing-plot-charity-founder-says.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/2022/07/15/uk-issues-red-extreme-heat-warning-braces-for-temperature-surge-.html
https://www.cnbc.com/2022/07/15/uk-issues-red-extreme-heat-warning-braces-for-temperature-surge-.html
https://www.cnbc.com/anmar-frangoul-profile--cnbc/
https://www.cnbc.com/coronavirus/
https://www.cnbc.com/2022/08/24/singapore-non-fully-vaccinated-travelers-dont-need-quarantine-from-monday.html
https://www.cnbc.com/2022/08/24/singapore-non-fully-vaccinated-travelers-dont-need-quarantine-from-monday.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/23/monkeypox-scientists-worry-virus-could-infect-animals-.html
https://www.cnbc.com/2022/08/23/monkeypox-scientists-worry-virus-could-infect-animals-.html
https://www.cnbc.com/spencer-kimball/
https://www.cnbc.com/2022/08/20/fda-authorizes-emergency-use-for-novavax-covid-19-vaccine-for-ages-12-and-17-.html
https://www.cnbc.com/2022/08/20/fda-authorizes-emergency-use-for-novavax-covid-19-vaccine-for-ages-12-and-17-.html
https://www.cnbc.com/annie-nova/
https://www.cnbc.com/2022/08/19/how-chinas-covid-policies-lead-to-hampered-supply-chains-higher-inflation.html
https://www.cnbc.com/2022/08/19/how-chinas-covid-policies-lead-to-hampered-supply-chains-higher-inflation.html
https://www.cnbc.com/noah-higgins-dunn/
https://www.cnbc.com/2022/08/18/monkeypox-us-to-provide-vaccines-for-pride-other-events-attended-by-gay-men.html
https://www.cnbc.com/2022/08/18/monkeypox-us-to-provide-vaccines-for-pride-other-events-attended-by-gay-men.html
https://www.cnbc.com/spencer-kimball/
https://www.cnbc.com/cnbc-travel/
https://www.cnbc.com/2022/08/26/how-to-find-cheap-hotel-rooms-survey-compares-popular-website-rates.html
https://www.cnbc.com/2022/08/26/how-to-find-cheap-hotel-rooms-survey-compares-popular-website-rates.html
https://www.cnbc.com/monica-pitrelli/
https://www.cnbc.com/2022/08/25/unlimited-caviar-and-popcorn-how-emirates-is-wooing-luxury-travelers.html
https://www.cnbc.com/2022/08/25/unlimited-caviar-and-popcorn-how-emirates-is-wooing-luxury-travelers.html
https://www.cnbc.com/lee-ying-shan/
https://www.cnbc.com/2022/08/22/how-much-does-it-cost-to-travel-full-time-heres-what-one-couple-pays.html
https://www.cnbc.com/2022/08/22/how-much-does-it-cost-to-travel-full-time-heres-what-one-couple-pays.html
https://www.cnbc.com/monica-pitrelli/
https://www.cnbc.com/2022/08/19/where-are-the-best-places-to-travel-in-spain-see-what-locals-say.html
https://www.cnbc.com/2022/08/19/where-are-the-best-places-to-travel-in-spain-see-what-locals-say.html
https://www.cnbc.com/lucy-handley/
https://www.cnbc.com/2022/08/17/what-to-do-on-the-island-of-jersey-beaches-food-hotels-and-tunnels.html
https://www.cnbc.com/2022/08/17/what-to-do-on-the-island-of-jersey-beaches-food-hotels-and-tunnels.html
https://www.cnbc.com/lucy-handley/
https://www.cnbc.com/make-it/
https://www.cnbc.com/video/2022/08/26/career-advice-take-at-least-one-risk-per-day-ceo-says.html
https://www.cnbc.com/video/2022/08/26/career-advice-take-at-least-one-risk-per-day-ceo-says.html
https://www.cnbc.com/2022/08/26/parenting-tips-randi-zuckerberg-on-kids-and-the-metaverse-screen-time.html
https://www.cnbc.com/2022/08/26/parenting-tips-randi-zuckerberg-on-kids-and-the-metaverse-screen-time.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/25/should-you-request-a-refund-on-student-loan-payments-made-during-pause.html
https://www.cnbc.com/2022/08/25/should-you-request-a-refund-on-student-loan-payments-made-during-pause.html
https://www.cnbc.com/morgan-smith/
https://www.cnbc.com/2022/08/25/housing-recession-home-price-decline-unlikely-despite-slowing-sales.html
https://www.cnbc.com/2022/08/25/housing-recession-home-price-decline-unlikely-despite-slowing-sales.html
https://www.cnbc.com/mike-winters/
https://www.cnbc.com/2022/08/25/pig-butchering-crypto-scam-costing-investors-millions.html
https://www.cnbc.com/2022/08/25/pig-butchering-crypto-scam-costing-investors-millions.html
https://www.cnbc.com/cheyenne-devon/
https://www.cnbc.com/investing-in-supertrends/
https://www.cnbc.com/2022/08/18/web3-is-in-chaos-metaverses-in-walled-gardens-randi-zuckerberg.html
https://www.cnbc.com/2022/08/18/web3-is-in-chaos-metaverses-in-walled-gardens-randi-zuckerberg.html
https://www.cnbc.com/goh-chiew-tong/
https://www.cnbc.com/2022/08/17/japan-support-for-nuclear-restart-is-highest-since-fukushima-disaster.html
https://www.cnbc.com/2022/08/17/japan-support-for-nuclear-restart-is-highest-since-fukushima-disaster.html
https://www.cnbc.com/lee-ying-shan/
https://www.cnbc.com/2022/08/10/india-australia-singapore-firms-jobs-are-in-these-sectors-linkedin.html
https://www.cnbc.com/2022/08/10/india-australia-singapore-firms-jobs-are-in-these-sectors-linkedin.html
https://www.cnbc.com/charmaine-jacob/
https://www.cnbc.com/2022/08/08/baidus-robotaxis-dont-need-any-human-staff-in-these-parts-of-china.html

In [10]:
#8
from bs4 import BeautifulSoup
import requests
import pandas as pd
url='https://www.journals.elsevier.com/artificial-intelligence/most-downloaded-articles'
page = requests.get(url)

soup = BeautifulSoup(page.text,'lxml')

paper_title=soup.find('a', class_="sc-5smygv-0 nrDZj")
paper_title

author = soup.find('span', class_='sc-1w3fpd7-0 pgLAT')
author.text

published_date = soup.find('span', class_='sc-1thf9ly-2 bKddwo')
published_date.text

paper_url = []
for link in soup.findAll("a"):
    if 'href' in link.attrs:
        print(link.attrs['href'])
paper_url

#skip-to-content-anchor
http://www.elsevier.com
https://account.elsevier.com/auth
https://elsevier.com/about
https://www.elsevier.com/connect
https://www.elsevier.com/about/careers
https://elsevier.com/about
https://www.elsevier.com/connect
https://www.elsevier.com/about/careers
https://www.elsevier.com/rd-solutions
https://www.elsevier.com/clinical-solutions
https://www.elsevier.com/research-platforms
https://www.elsevier.com/research-intelligence
https://www.elsevier.com/education
https://www.elsevier.com/solutions
https://www.elsevier.com/rd-solutions
https://www.elsevier.com/clinical-solutions
https://www.elsevier.com/research-platforms
https://www.elsevier.com/research-intelligence
https://www.elsevier.com/education
https://www.elsevier.com/solutions
https://www.elsevier.com/authors
https://www.elsevier.com/editors
https://www.elsevier.com/reviewers
https://www.elsevier.com/librarians
https://www.elsevier.com/strategic-partners
https://www.elsevier.com/open-access
https://www.elsevier.com/societies
https://www.elsevier.com/authors
https://www.elsevier.com/editors
https://www.elsevier.com/reviewers
https://www.elsevier.com/librarians
https://www.elsevier.com/strategic-partners
https://www.elsevier.com/open-access
https://www.elsevier.com/societies
https://www.elsevier.com/books-and-journals
https://webshop.elsevier.com/?utm_source=ecom&utm_medium=top&utm_campaign=webshop
https://www.elsevier.com/books-and-journals
https://webshop.elsevier.com/?utm_source=ecom&utm_medium=top&utm_campaign=webshop
https://global-checkout.elsevier.com
https://account.elsevier.com/auth
https://www.sciencedirect.com/science/journal/00043702
https://www.editorialmanager.com/artint/default.aspx
https://www.elsevier.com/
https://www.elsevier.com/search-results?labels=journals
/artificial-intelligence
/artificial-intelligence/most-downloaded-articles
https://www.sciencedirect.com/science/journal/00043702
https://www.editorialmanager.com/artint/default.aspx
https://www.sciencedirect.com/science/journal/00043702
https://www.elsevier.com/journals/artificial-intelligence/0004-3702/guide-for-authors
https://www.editorialmanager.com/artint/default.aspx
https://authors.elsevier.com/tracking/landingpage/selection.do
https://www.elsevier.com/journals/artificial-intelligence/0004-3702/subscribe?subscriptiontype=institutional
https://www.sciencedirect.com/science/article/pii/S0004370221000862
https://www.sciencedirect.com/science/article/pii/S0004370221000722
https://www.sciencedirect.com/science/article/pii/S0004370215000910
https://www.sciencedirect.com/science/article/pii/S0004370298000551
https://www.sciencedirect.com/science/article/pii/S0004370216300790
https://www.sciencedirect.com/science/article/pii/S0004370218305988
https://www.sciencedirect.com/science/article/pii/S0004370220301855
https://www.sciencedirect.com/science/article/pii/S0004370214001386
https://www.sciencedirect.com/science/article/pii/S0004370299000521
https://www.sciencedirect.com/science/article/pii/S0004370219300116
https://www.sciencedirect.com/science/article/pii/S0004370220301533
https://www.sciencedirect.com/science/article/pii/S0004370207000793
https://www.sciencedirect.com/science/article/pii/S0004370216300285
https://www.sciencedirect.com/science/article/pii/S0004370220301958
https://www.sciencedirect.com/science/article/pii/S0004370297000635
https://www.sciencedirect.com/science/article/pii/S0004370221000515
https://www.sciencedirect.com/science/article/pii/S0004370221000539
https://www.sciencedirect.com/science/article/pii/S0004370221000096
https://www.sciencedirect.com/science/article/pii/S0004370216300868
https://www.sciencedirect.com/science/article/pii/S0004370221000588
https://www.sciencedirect.com/science/article/pii/S0004370221000102
https://www.sciencedirect.com/science/article/pii/S0004370213001082
https://www.sciencedirect.com/science/article/pii/S000437029700043X
https://www.sciencedirect.com/science/article/pii/S0004370221000734
https://www.sciencedirect.com/science/article/pii/S0004370209001398
https://www.sciencedirect.com/science/journal/00043702
https://www.sciencedirect.com/user/alerts
https://www.sciencedirect.com/user/register?utm_campaign=sd_recommender_ELSJLS&utm_channel=elseco&dgcid=sd_recommender_ELSJLS
http://www.elsevier.com/authors/home
https://www.editorialmanager.com/artint/default.aspx
https://www.editorialmanager.com/artint/default.aspx
https://researcheracademy.elsevier.com
https://www.elsevier.com/about/policies/copyright/permissions
https://webshop.elsevier.com
https://service.elsevier.com/app/home/supporthub/publishing/#authors
https://authors.elsevier.com/tracking/landingpage/selection.do
https://www.elsevier.com/librarians
https://www.elsevier.com/journals/artificial-intelligence/0004-3702/subscribe?subscriptiontype=institutional
http://www.elsevier.com/editors
http://www.elsevier.com/editors/perk
https://www.elsevier.com/editors/guest-editors
https://service.elsevier.com/app/home/supporthub/publishing/#editors
http://www.elsevier.com/reviewers
https://www.elsevier.com/reviewers/how-to-review
https://www.editorialmanager.com/artint/default.aspx
https://www.elsevier.com/reviewers/becoming-a-reviewer-how-and-why#recognizing
https://service.elsevier.com/app/home/supporthub/publishing/#reviewers
https://www.elsevier.com
//www.elsevier.com/legal/elsevier-website-terms-and-conditions
//www.elsevier.com/legal/privacy-policy
//www.elsevier.com/legal/cookienotice
//www.elsevier.com/sitemap
https://www.relx.com/

[]

In [6]:
#8
paper_titles = []

for i in soup.find_all('a', class_="sc-5smygv-0 nrDZj"):
    paper_titles.append(i.text)
paper_titles

['Reward is enough',
 'Making sense of raw input',
 'Law and logic: A review from an argumentation perspective',
 'Creativity and artificial intelligence',
 'Artificial cognition for social human–robot interaction: An implementation',
 'Explanation in artificial intelligence: Insights from the social sciences',
 'Making sense of sensory input',
 'Conflict-based search for optimal multi-agent pathfinding',
 'Between MDPs and semi-MDPs: A framework for temporal abstraction in reinforcement learning',
 'The Hanabi challenge: A new frontier for AI research',
 'Evaluating XAI: A comparison of rule-based and example-based explanations',
 'Argumentation in artificial intelligence',
 'Algorithms for computing strategies in two-player simultaneous move games',
 'Multiple object tracking: A literature review',
 'Selection of relevant features and examples in machine learning',
 'A survey of inverse reinforcement learning: Challenges, methods and progress',
 'Explaining individual predictions when features are dependent: More accurate approximations to Shapley values',
 'A review of possible effects of cognitive biases on interpretation of rule-based machine learning models',
 'Integrating social power into the decision-making of cognitive agents',
 "“That's (not) the output I expected!” On the role of end user expectations in creating explanations of AI systems",
 'Explaining black-box classifiers using post-hoc explanations-by-example: The effect of explanations and error-rates in XAI user studies',
 'Algorithm runtime prediction: Methods & evaluation',
 'Wrappers for feature subset selection',
 'Commonsense visual sensemaking for autonomous driving – On generalised neurosymbolic online abduction integrating vision and semantics',
 'Quantum computation, quantum theory and AI']

In [7]:
#8
author = []

for i in soup.find_all('span', class_='sc-1w3fpd7-0 pgLAT'):
    author.append(i.text)
author

['Silver, David, Singh, Satinder, Precup, Doina, Sutton, Richard S. ',
 'Evans, Richard, Bošnjak, Matko and 5 more',
 'Prakken, Henry, Sartor, Giovanni ',
 'Boden, Margaret A. ',
 'Lemaignan, Séverin, Warnier, Mathieu and 3 more',
 'Miller, Tim ',
 'Evans, Richard, Hernández-Orallo, José and 3 more',
 'Sharon, Guni, Stern, Roni, Felner, Ariel, Sturtevant, Nathan R. ',
 'Sutton, Richard S., Precup, Doina, Singh, Satinder ',
 'Bard, Nolan, Foerster, Jakob N. and 13 more',
 'van der Waa, Jasper, Nieuwburg, Elisabeth, Cremers, Anita, Neerincx, Mark ',
 'Bench-Capon, T.J.M., Dunne, Paul E. ',
 'Bošanský, Branislav, Lisý, Viliam and 3 more',
 'Luo, Wenhan, Xing, Junliang and 4 more',
 'Blum, Avrim L., Langley, Pat ',
 'Arora, Saurabh, Doshi, Prashant ',
 'Aas, Kjersti, Jullum, Martin, Løland, Anders ',
 'Kliegr, Tomáš, Bahník, Štěpán, Fürnkranz, Johannes ',
 'Pereira, Gonçalo, Prada, Rui, Santos, Pedro A. ',
 'Riveiro, Maria, Thill, Serge ',
 'Kenny, Eoin M., Ford, Courtney, Quinn, Molly, Keane, Mark T. ',
 'Hutter, Frank, Xu, Lin, Hoos, Holger H., Leyton-Brown, Kevin ',
 'Kohavi, Ron, John, George H. ',
 'Suchan, Jakob, Bhatt, Mehul, Varadarajan, Srikrishna ',
 'Ying, Mingsheng ']

In [8]:
#8
published_date = []

for i in soup.find_all('span', class_='sc-1thf9ly-2 bKddwo'):
    published_date.append(i.text)
published_date

['October 2021',
 'October 2021',
 'October 2015',
 'August 1998',
 'June 2017',
 'February 2019',
 'April 2021',
 'February 2015',
 'August 1999',
 'March 2020',
 'February 2021',
 'October 2007',
 'August 2016',
 'April 2021',
 'December 1997',
 'August 2021',
 'September 2021',
 'June 2021',
 'December 2016',
 'September 2021',
 'May 2021',
 'January 2014',
 'December 1997',
 'October 2021',
 'February 2010']

In [6]:
#9
from bs4 import BeautifulSoup
import requests
import pandas as pd
page = requests.get('https://www.dineout.co.in/delhi-restaurants/buffet-special')
page
soup = BeautifulSoup(page.content)
soup
names = []

for i in soup.find_all('div',class_="restnt-info cursor"):
    names.append(i.text)
    
names
locations = []

for i in soup.find_all('div',class_="restnt-loc ellipsis"):
    locations.append(i.text)
    
locations
price = []

for i in soup.find_all('span',class_="double-line-ellipsis"):
    price.append(i.text)
    
price
images = []

for i in soup.find_all("img",class_="no-img"):
    images.append(i['data-src'])
    
images
import pandas as pd
df = pd.DataFrame({'Names':names,'Locations':locations,'Price and Cuisine':price,'Images_url':images})
df

,Names,Locations,Price and Cuisine,Images_url
0,"Castle BarbequeConnaught Place, Central Delhi","Connaught Place, Central Delhi","₹ 2,000 for 2 (approx) | Chinese, North Indian",https://im1.dineout.co.in/images/uploads/resta...
1,"Jungle Jamboree3CS Mall,Lajpat Nagar - 3, Sout...","3CS Mall,Lajpat Nagar - 3, South Delhi","₹ 1,680 for 2 (approx) | North Indian, Asian, ...",https://im1.dineout.co.in/images/uploads/resta...
2,"Castle BarbequePacific Mall,Tagore Garden, Wes...","Pacific Mall,Tagore Garden, West Delhi","₹ 2,000 for 2 (approx) | Chinese, North Indian",https://im1.dineout.co.in/images/uploads/resta...
3,"Cafe KnoshThe Leela Ambience Convention Hotel,...","The Leela Ambience Convention Hotel,Shahdara, ...","₹ 3,000 for 2 (approx) | Italian, Continental",https://im1.dineout.co.in/images/uploads/resta...
4,"The Barbeque CompanyGardens Galleria,Sector 38...","Gardens Galleria,Sector 38A, Noida","₹ 1,700 for 2 (approx) | North Indian, Chinese",https://im1.dineout.co.in/images/uploads/resta...
5,"India GrillHilton Garden Inn,Saket, South Delhi","Hilton Garden Inn,Saket, South Delhi","₹ 2,400 for 2 (approx) | North Indian, Italian",https://im1.dineout.co.in/images/uploads/resta...
6,"Delhi BarbequeTaurus Sarovar Portico,Mahipalpu...","Taurus Sarovar Portico,Mahipalpur, South Delhi","₹ 1,800 for 2 (approx) | North Indian",https://im1.dineout.co.in/images/uploads/resta...
7,The Monarch - Bar Be Que VillageIndirapuram Ha...,"Indirapuram Habitat Centre,Indirapuram, Ghaziabad","₹ 1,900 for 2 (approx) | North Indian",https://im1.dineout.co.in/images/uploads/resta...
8,"Indian Grill RoomSuncity Business Tower,Golf C...","Suncity Business Tower,Golf Course Road, Gurgaon","₹ 2,200 for 2 (approx) | North Indian, Mughlai",https://im1.dineout.co.in/images/uploads/resta...

In [2]:
#10
from bs4 import BeautifulSoup
import requests
import pandas as pd
import re

url = 'https://scholar.google.com/citations?view_op=top_venues&hl=en'
page = requests.get(url)
page

soup = BeautifulSoup(page.content, "html.parser")

first_title=soup.find('th', class_="gsc_mvt_t")
first_title.text
'Publication'

index = soup.find('th', class_='gsc_mvt_n')
index.text


median = soup.find('span', class_="gs_ibl gsc_mp_anchor")
median.text

publication = []

for i in soup.find_all('td', class_="gsc_mvt_t"):
    publication.append(i.text)
publication

['Nature',
 'The New England Journal of Medicine',
 'Science',
 'IEEE/CVF Conference on Computer Vision and Pattern Recognition',
 'The Lancet',
 'Advanced Materials',
 'Nature Communications',
 'Cell',
 'International Conference on Learning Representations',
 'Neural Information Processing Systems',
 'JAMA',
 'Chemical Reviews',
 'Proceedings of the National Academy of Sciences',
 'Angewandte Chemie',
 'Chemical Society Reviews',
 'Journal of the American Chemical Society',
 'IEEE/CVF International Conference on Computer Vision',
 'Nucleic Acids Research',
 'International Conference on Machine Learning',
 'Nature Medicine',
 'Renewable and Sustainable Energy Reviews',
 'Science of The Total Environment',
 'Advanced Energy Materials',
 'Journal of Clinical Oncology',
 'ACS Nano',
 'Journal of Cleaner Production',
 'Advanced Functional Materials',
 'Physical Review Letters',
 'Scientific Reports',
 'The Lancet Oncology',
 'Energy & Environmental Science',
 'IEEE Access',
 'PLoS ONE',
 'Science Advances',
 'Journal of the American College of Cardiology',
 'Applied Catalysis B: Environmental',
 'Nature Genetics',
 'BMJ',
 'Circulation',
 'European Conference on Computer Vision',
 'International Journal of Molecular Sciences',
 'Nature Materials',
 'Chemical engineering journal',
 'AAAI Conference on Artificial Intelligence',
 'Journal of Materials Chemistry A',
 'ACS Applied Materials & Interfaces',
 'Nature Biotechnology',
 'The Lancet Infectious Diseases',
 'Frontiers in Immunology',
 'Applied Energy',
 'Nano Energy',
 'Nature Energy',
 'Meeting of the Association for Computational Linguistics (ACL)',
 'The Astrophysical Journal',
 'Gastroenterology',
 'Nature Methods',
 'IEEE Transactions on Pattern Analysis and Machine Intelligence',
 'Cochrane Database of Systematic Reviews',
 'Blood',
 'Neuron',
 'Nano Letters',
 'Morbidity and Mortality Weekly Report',
 'European Heart Journal',
 'Nature Nanotechnology',
 'ACS Catalysis',
 'Nature Neuroscience',
 'American Economic Review',
 'Journal of High Energy Physics',
 'IEEE Communications Surveys & Tutorials',
 'Annals of Oncology',
 'Nutrients',
 'Accounts of Chemical Research',
 'Immunity',
 'Environmental Science & Technology',
 'Nature Reviews. Molecular Cell Biology',
 'Gut',
 'Physical Review D',
 'ACS Energy Letters',
 'Monthly Notices of the Royal Astronomical Society',
 'Conference on Empirical Methods in Natural Language Processing (EMNLP)',
 'Clinical Infectious Diseases',
 'Cell Metabolism',
 'Nature Reviews Immunology',
 'Joule',
 'Nature Photonics',
 'International Journal of Environmental Research and Public Health',
 'Environmental Pollution',
 'Computers in Human Behavior',
 'Frontiers in Microbiology',
 'Nature Physics',
 'Small',
 'Cell Reports',
 'Molecular Cell',
 'Clinical Cancer Research',
 'Bioresource Technology',
 'Journal of Business Research',
 'Molecular Cancer',
 'Sensors',
 'Nature Climate Change',
 'IEEE Internet of Things Journal']

In [3]:
index = []

for i in soup.find_all('td', class_="gsc_mvt_n"):
    index.append(i.text)

index

['444',
 '667',
 '432',
 '780',
 '401',
 '614',
 '389',
 '627',
 '354',
 '635',
 '312',
 '418',
 '307',
 '428',
 '300',
 '505',
 '286',
 '533',
 '278',
 '436',
 '267',
 '425',
 '265',
 '444',
 '256',
 '364',
 '245',
 '332',
 '244',
 '386',
 '242',
 '344',
 '239',
 '415',
 '238',
 '550',
 '237',
 '421',
 '235',
 '389',
 '227',
 '324',
 '225',
 '311',
 '220',
 '300',
 '213',
 '315',
 '211',
 '277',
 '211',
 '273',
 '210',
 '280',
 '207',
 '294',
 '206',
 '274',
 '202',
 '329',
 '202',
 '290',
 '200',
 '303',
 '198',
 '278',
 '197',
 '294',
 '195',
 '276',
 '192',
 '246',
 '191',
 '297',
 '190',
 '307',
 '189',
 '301',
 '186',
 '321',
 '183',
 '253',
 '181',
 '265',
 '181',
 '224',
 '180',
 '296',
 '178',
 '220',
 '177',
 '223',
 '175',
 '315',
 '173',
 '296',
 '173',
 '228',
 '173',
 '217',
 '172',
 '232',
 '170',
 '314',
 '169',
 '304',
 '167',
 '234',
 '166',
 '254',
 '165',
 '296',
 '165',
 '293',
 '165',
 '243',
 '165',
 '229',
 '164',
 '231',
 '164',
 '207',
 '163',
 '302',
 '163',
 '265',
 '163',
 '264',
 '163',
 '220',
 '162',
 '248',
 '160',
 '263',
 '160',
 '220',
 '159',
 '304',
 '159',
 '243',
 '159',
 '214',
 '159',
 '211',
 '158',
 '242',
 '158',
 '214',
 '155',
 '340',
 '155',
 '235',
 '155',
 '217',
 '155',
 '212',
 '155',
 '194',
 '154',
 '249',
 '153',
 '278',
 '153',
 '211',
 '152',
 '292',
 '152',
 '233',
 '152',
 '228',
 '152',
 '225',
 '152',
 '222',
 '152',
 '214',
 '151',
 '225',
 '151',
 '222',
 '150',
 '196',
 '149',
 '205',
 '149',
 '202',
 '146',
 '201',
 '146',
 '190',
 '145',
 '233',
 '145',
 '209',
 '145',
 '201',
 '144',
 '228',
 '144',
 '212']